
Vagrant.configure("2") do |config|
  config.vm.provider "libvirt" do |libvirt|
    libvirt.machine_virtual_size = "128GB"
    libvirt.memory = "2048"
    libvirt.cpus = "2"

    libvirt.cpu_mode = "custom"
    libvirt.cpu_model = "qemu32"
    #libvirt.cpu_model = "cortex-a53"
    #libvirt.cpu_model = "cortex-a9"

    #libvirt.os.type = "hvm"  # hvm,kvm,paravirtualization; 
    #libvirt.os.arch = "armhf"  # arm,armhf,aarch64,x86_64
    #libvirt.os.machine = "virt" # influences qemu 'cpu' model indirectly
  end
end

