Vagrant.configure("2") do |config|
    config.vm.provider :libvirt do |libvirt|
        libvirt.machine_virtual_size = 40
        libvirt.memory = 4096
        libvirt.cpus = 4
    end

    config.vm.network "private_network",
        ip: "192.168.121.63",
        libvirt__network_name: "vagrant-libvirt",
        libvirt__dhcp_enabled: false,
        libvirt__forward_mode: "nat"

    config.vm.box = "almalinux/10"

    config.vm.synced_folder ENV.fetch("ZROK_SOURCE", "#{ENV['HOME']}/Sites/netfoundry/github/zrok"),
        "/srv/zrok",
        type: "rsync",
        rsync__exclude: [".git/", "node_modules/", ".cache/", "website/"]

    config.vm.provision "ansible", run: "once" do |ansible|
        ansible.verbose = "v"
        ansible.playbook = "playbook.yaml"
        ansible.extra_vars = {
            ziti_bootstrap_mode: "noninteractive",
            zrok2_store_type: "postgres",
            ansible_python_interpreter: "/usr/bin/python3",
        }
    end
end
