Vagrant.configure("2") do |config|
    config.vm.box = "centos/7"
    config.vm.provision "ansible", run: "once" do |ansible|
        ansible.verbose = "v"
        ansible.playbook = "playbook_centos_install_docker.yaml"
    end
    config.vm.provision :reload, run: "once"
    config.vm.provision "ansible", run: "always" do |ansible|
        ansible.verbose = "v"
        ansible.playbook = "playbook_centos_install_ziti.yaml"
        ansible.extra_vars = { ansible_python_interpreter: "/usr/bin/python3" }
    end
end