- name: Set up zrok Package Repo
  gather_facts: true
  hosts: all
  become: true
  tasks:
    - name: Set up apt repo
      when: ansible_os_family == "Debian"
      block:
        - name: Install playbook dependencies
          ansible.builtin.package:
            name:
              - gnupg
            state: present
    - name: Set up yum repo
      when: ansible_os_family == "RedHat"
      block:
        - meta: noop

# - name: Install zrok-share package
#   gather_facts: false
#   hosts: all 
#   become: true
#   tasks:
#   - name: Install zrok-share
#     ansible.builtin.package:
#       name: zrok-share
#       state: present
