- name: Set up zrok Package Repo
  gather_facts: true
  hosts: all
  become: true
  tasks:
    - name: Set up apt repo
      when: ansible_os_family == "Debian"
      block:
        - name: Install playbook dependencies
          ansible.builtin.apt:
            update_cache: true
            name:
              - gnupg
            state: present
    - name: Set up yum repo
      when: ansible_os_family == "RedHat"
      block:
        - name: Configure OpenZiti RPM Repo
          ansible.builtin.yum_repository:
            name: OpenZitiTest
            description: OpenZiti Test
            baseurl: >-
              https://packages.openziti.org/zitipax-openziti-rpm-test/redhat/$basearch
            enabled: 'yes'
            gpgkey: >-
              https://packages.openziti.org/zitipax-openziti-rpm-test/redhat/$basearch/repodata/repomd.xml.key
            repo_gpgcheck: 'yes'
            gpgcheck: 'no'

        - name: Update yum cache
          ansible.builtin.yum:
            update_cache: true

    - name: Install extra packages
      ansible.builtin.package:
        name:
          - tree
          - vim
          - git
        state: present
