
Vagrant.configure("2") do |config|
    config.vm.provider :libvirt do |libvirt|
        libvirt.machine_virtual_size = 128
    end

    # config.vm.box = "generic-x64/ubuntu2310"   # connection refused (libvirt error)
    # config.vm.box = "generic-x64/ubuntu2304"  # 
    # config.vm.box = "generic/ubuntu2204"      # 
    # config.vm.box = "generic/ubuntu2004"      # 
    # config.vm.box = "rockylinux/9"            # 

    # config.vm.box = "rockylinux/8"            # 
    # config.vm.box_version = "5.0.0"
    # growfs server

    # config.vm.box = "generic/debian10"        # panic: user: unknown userid 64342
    config.vm.box = "generic/debian11"        # 
    # config.vm.box = "generic/debian12"        # 
    # config.vm.box = "generic-x64/fedora39"
    # config.vm.box = "generic-x64/fedora38"    # 
    # config.vm.box = "generic-x64/fedora37"    # 

    # config.vm.box = "generic/ubuntu1804"      # undefined STATE_DIRECTORY
    # config.vm.box = "centos/7"                # undefined STATE_DIRECTORY

    config.vm.provision "ansible", run: "once" do |ansible|
        ansible.verbose = "vvv"
        # ansible.verbose = "v"
        ansible.playbook = "playbook.yaml"
        # ansible.extra_vars = { ansible_python_interpreter: "/usr/bin/python3" }
    end

    # Docker provisioner configuration
    config.vm.provision :docker

    # config.vm.provision "shell", inline: <<-SHELL
    #     # Install Docker Compose
    #     sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
    #     sudo chmod +x /usr/local/bin/docker-compose
    # SHELL

    # config.vm.provision "shell", inline: <<-SHELL
    #     set -euo pipefail
    #     apt-get install -y ansible
    #     ansible-galaxy collection install \
    #         git+https://github.com/openziti-test-kitchen/ansible-collection.git,repo-playbook
    #     ansible-playbook community.openziti.install_ziti_cli --connection local --inventory localhost,
    # SHELL

end