- name: zrok-share
  gather_facts: false
  hosts: default
  become: true

  tasks:

  - name: Install dependencies
    package:
      name: [curl, gnupg]
      state: present

  - name: Install zrok-share package from repo
    shell: >
      curl https://raw.githubusercontent.com/openziti/ziti/release-next/dist/dist-packages/linux/install.bash
      | bash -xs zrok-share
    environment:
      ZITIPAX_DEB: zitipax-fork-deb-stable
      ZITIPAX_RPM: zitipax-fork-rpm-stable

  - name: Place env config
    copy:
      dest: /opt/openziti/etc/zrok/zrok-share.env
      src: /opt/openziti/etc/zrok/zrok-share.env

  - name: Enable and restart service
    systemd:
      name: zrok-share
      enabled: yes
      state: restarted
      daemon_reload: yes

  - name: Wait for service
    systemd:
      name: zrok-share
      state: started
    register: service_status
    until: service_status.status.ActiveState == 'active'
    retries: 30
    delay: 1
