
Vagrant.configure("2") do |config|
    config.vm.provider :libvirt do |libvirt|
        libvirt.machine_virtual_size = 10
    end

    # config.vm.box = "generic-x64/ubuntu2310"   # connection refused (libvirt error)
    # config.vm.box = "generic-x64/ubuntu2304"  # v30
    # config.vm.box = "generic/ubuntu2204"      # v30
    # config.vm.box = "generic/ubuntu2004"      # v30
    # config.vm.box = "rockylinux/9"            # v30

    config.vm.box = "rockylinux/8"            # v30
    # config.vm.box_version = "5.0.0"
    # growfs server

    # config.vm.box = "generic/debian10"        # panic: user: unknown userid 64342
    # config.vm.box = "generic/debian11"        # v30
    # config.vm.box = "generic/debian12"        # v30
    # config.vm.box = "generic-x64/fedora38"    # v30
    # config.vm.box = "generic-x64/fedora37"    # v30

    # config.vm.box = "generic/ubuntu1804"      # undefined STATE_DIRECTORY
    # config.vm.box = "centos/7"                # undefined STATE_DIRECTORY
    config.vm.provision "ansible", run: "once" do |ansible|
        ansible.verbose = "vvv"
        # ansible.verbose = "v"
        ansible.playbook = "playbook.yaml"
        # ansible.extra_vars = { ansible_python_interpreter: "/usr/bin/python3" }
    end
end