Vagrant.configure("2") do |config|
    # config.vm.box = "generic/ubuntu2204"   # v25 
    # config.vm.box = "generic/ubuntu2004"   # v27
    # config.vm.box = "generic/ubuntu1804"   # fail with undefined STATE_DIRECTORY
    # config.vm.box = "rockylinux/8"         # fail no IP address
    # config.vm.box = "rockylinux/9"         # v28
    # config.vm.box = "generic-x64/fedora38" # v28
    config.vm.box = "generic-x64/fedora37"
    config.vm.provision "ansible", run: "once" do |ansible|
        ansible.verbose = "vvv"
        # ansible.verbose = "v"
        ansible.playbook = "playbook.yaml"
        # ansible.extra_vars = { ansible_python_interpreter: "/usr/bin/python3" }
    end
end