---
- name: Bootstrap Development Environment
  gather_facts: false
  hosts: all
  become: no

  tasks:
    - name: Install Python
      become: yes
      ansible.builtin.raw: |
        pkg update
        pkg upgrade -y
        pkg install -y python

    - name: Install packages
      become: yes
      ansible.builtin.pkgng:
        name:
          - cmake
          - expect
          - gcc
          - git
          - gmake
          - ninja
          - pkgconf
          - portsnap
          - rsync
          - vim
          - zip
          - zlib-ng
        state: present

    - name: Install Ports
      become: yes
      ansible.builtin.shell: |
        set -euxo pipefail
        portsnap fetch
        portsnap extract
        portsnap update
      args:
        creates: /usr/ports

    - name: Install Go 1.21 from Ports
      ansible.builtin.shell: |
        set -euxo pipefail
        make install clean
        ln -sfvn /usr/local/go121/bin/go /usr/local/bin/go
      become: yes
      args:
        chdir: /usr/ports/lang/go121
        creates: /usr/local/go121/bin/go

    - name: Set Environment Variables
      ansible.builtin.blockinfile:
        # path: /etc/profile.d/go.sh
        path: ~/.bashrc
        create: yes
        block: |
          export GOROOT=/usr/local/go121
          export GOPATH=$HOME/go
          export PATH=$PATH:$GOROOT/bin:$GOPATH/bin
      # become: yes

    - name: clone vcpkg
      ansible.builtin.git:
        repo: https://github.com/microsoft/vcpkg.git
        version: 2024.02.14
        single_branch: yes
        dest: /home/vagrant/vcpkg

    - name: bootstrap vcpkg
      ansible.builtin.shell: |
        set -euxo pipefail
        ./bootstrap-vcpkg.sh
      args:
        chdir: /home/vagrant/vcpkg
        creates: /home/vagrant/vcpkg/vcpkg

    # decided to use `vagrant rsync` to keep the checkout in sync with the vagrant box
    # - name: clone ziti-sdk-c
    #   ansible.builtin.git:
    #     repo: https://github.com/openziti/ziti-sdk-c.git
    #     version: 0.36.5
    #     single_branch: yes
    #     dest: /home/vagrant/ziti-sdk-c
    #   when: clone_ziti_sdk_c == "true"

    # - name: build ziti-sdk-c
    #   ansible.builtin.shell: |
    #     set -euxo pipefail
    #     mkdir build
    #     cd build
    #     cmake --preset ci-freebsd-x64 -Dtlsuv_DIR=${HOME}/tlsuv ..
    #     cmake --build .
    #   environment:
    #     VCPKG_ROOT: /home/vagrant/vcpkg
    #   args:
    #     chdir: /home/vagrant/ziti-sdk-c
    #     creates: /home/vagrant/ziti-sdk-c/build