---

- name: Bootstrap Development Environment
  gather_facts: false
  hosts: all
  become: false

  vars:
    goroot: /usr/local/go121
    gopath: /home/vagrant/go
    clone_all: "false"
    repos:
      - name: ziti-sdk-c
        version: freebsd
        clone: "false"
      - name: tlsuv
        version: main
        clone: "false"
      - name: ziti  # needed to run ziti-sdk-c tests
        version: main
        clone: "false"
      # - name: ziti-tunnel-sdk-c
      #   version: freebsd
      #   clone: "false"

  environment:
    GOROOT: "{{ goroot }}"
    GOPATH: "{{ gopath }}"

  tasks:
    - name: Install Python
      become: true
      ansible.builtin.raw: |
        pkg update
        pkg upgrade -y
        pkg install -y python

    - name: Install packages
      become: true
      community.general.pkgng:
        name:
          - cmake
          - expect
          - gcc
          - git
          - gmake
          - ninja
          - pkgconf
          - portsnap
          - rsync
          - vim
          - zip
          - zlib-ng
        state: present

    - name: Install Ports
      become: true
      ansible.builtin.shell: |
        set -euxo pipefail
        portsnap fetch
        portsnap extract
        portsnap update
      args:
        creates: /usr/ports

    - name: Install Go 1.21 from Ports
      ansible.builtin.shell: |
        set -euxo pipefail
        make install clean
        ln -sfvn /usr/local/go121/bin/go /usr/local/bin/go
      become: true
      args:
        chdir: /usr/ports/lang/go121
        creates: /usr/local/go121/bin/go

    - name: Clone vcpkg
      ansible.builtin.git:
        repo: https://github.com/microsoft/vcpkg.git
        version: 2024.02.14
        single_branch: true
        dest: /home/vagrant/vcpkg

    - name: Bootstrap vcpkg
      ansible.builtin.shell: |
        set -euxo pipefail
        ./bootstrap-vcpkg.sh
      args:
        chdir: /home/vagrant/vcpkg
        creates: /home/vagrant/vcpkg/vcpkg

    - name: Clone Ziti Projects
      ansible.builtin.git:
        repo: https://github.com/openziti/{{ item.name }}.git
        version: "{{ item.version }}"
        single_branch: true
        dest: /home/vagrant/{{ item.name }}/
      when: clone_all == "true" or item.clone == "true"
      loop: "{{ repos }}"

    - name: Build ziti-sdk-c
      ansible.builtin.shell: |
        set -euxo pipefail
        mkdir build
        cd build
        cmake --preset ci-freebsd-x64 -DZITI_CLI_VER=freebsd -Dtlsuv_DIR=${HOME}/tlsuv ..
        cmake --build .
      environment:
        VCPKG_ROOT: /home/vagrant/vcpkg
      args:
        chdir: /home/vagrant/ziti-sdk-c
        creates: /home/vagrant/ziti-sdk-c/build
