Vagrant.configure("2") do |config|
    config.vm.define "freebsd-tunnel" do |freebsd|
        freebsd.vm.provider :libvirt do |libvirt|
            libvirt.memory = 8192 # Amount of memory in MB
            libvirt.cpus = 8 # Number of CPUs
        end
        freebsd.vm.box = "generic/freebsd14"
        freebsd.vm.provision "ansible", run: "once" do |ansible|
            ansible.verbose = "vvv"
            ansible.playbook = "playbook.yml"
            ansible.extra_vars = {
                clone_all: ENV['ZITI_SOURCE'].nil? ? "true" : "false"
            }
        end

        if ENV['ZITI_SOURCE'] && !ENV['ZITI_SOURCE'].empty?
            ziti_source_path = ENV['ZITI_SOURCE']
            projects = ['ziti-sdk-c', 'tlsuv', 'ziti', 'ziti-tunnel-sdk-c']
            projects.each do |project|
                freebsd.vm.synced_folder "#{ziti_source_path}/#{project}", "/home/vagrant/#{project}"
            end
        end
    end
end
