Vagrant.configure("2") do |config|
    config.vm.provider :libvirt do |libvirt|
        libvirt.memory = 8192 # Amount of memory in MB
        libvirt.cpus = 8 # Number of CPUs
    end
    config.vm.box = "generic/freebsd14"
    config.vm.provision "ansible", run: "once" do |ansible|
        ansible.verbose = "vvv"
        ansible.playbook = "playbook.yml"
        ansible.extra_vars = {
            clone_ziti_sdk_c: "false"
        }
    end
    config.vm.synced_folder "/home/kbingham/Sites/netfoundry/github/ziti-sdk-c", "/home/vagrant/ziti-sdk-c"
end
