Vagrant.configure("2") do |config|
    config.vm.provider :libvirt do |libvirt|
        libvirt.storage :file, size: '20G', type: 'qcow2'
    end
    config.vm.box = "generic-x64/fedora37"    # v30
    # config.vm.box = "generic/alma9"
    # config.vm.box = "generic/alma8"
    config.vm.provision "ansible", run: "once" do |ansible|
        ansible.verbose = "v"
        ansible.playbook = "playbook.yaml"
    end
end