Vagrant.configure("2") do |config|

    config.vm.define "tunneler", primary: true do |tunneler|
        tunneler.vm.hostname = "tunneler"
        tunneler.vm.box = "bento/ubuntu-24.04"
        tunneler.vm.provision "ansible", run: "once" do |ansible|
            ansible.verbose = "v"
            ansible.playbook = "playbook.yaml"
            # ansible.extra_vars = { ansible_python_interpreter: "/usr/bin/python3" }
        end
    end
end