Vagrant.configure("2") do |config|
    config.vm.box = "sputnik13/trusty64"
    config.vm.provision "ansible", run: "once" do |ansible|
        ansible.verbose = "v"
        ansible.playbook = "playbook_install_ziti_edge_tunnel.yaml"
        ansible.extra_vars = { ansible_python_interpreter: "/usr/bin/python3" }
    end
end