Vagrant.configure("2") do |config|
    config.vm.box = "generic/rocky9"
    config.vm.provision "ansible", run: "once" do |ansible|
        ansible.verbose = "v"
        ansible.playbook = "playbook.yaml"
    end
end