- name: Install Ziti Edge Tunnel
  gather_facts: false
  hosts: tunneler
  become: true

  tasks:
    - name: Add Apt signing key
      ansible.builtin.apt_key:
        url: https://get.openziti.io/tun/package-repos.gpg
        state: present
    - name: Add specified repository into sources list
      ansible.builtin.apt_repository:
        repo: deb https://packages.openziti.org/zitipax-openziti-deb-stable focal main
        state: present
    - name: Install Ziti Edge Tunnel from DEB repo
      ansible.builtin.apt:
        name: ziti-edge-tunnel
        update_cache: true
    - name: Detect existing Ziti Identity
      ansible.builtin.stat:
        path: /opt/openziti/etc/identities/ziti-id.json
      register: ziti_id
    - name: Install Ziti Identity Enrollment Token
      ansible.builtin.copy:
        src: ./ziti-id.jwt  # relative to playbook on Vagrant host/Ansible Controller
        dest: /opt/openziti/etc/identities/ziti-id.jwt
        owner: root
        group: ziti
        mode: '0664'
      when: ziti_id.stat.exists == false
    - name: Start Ziti Edge Tunnel
      ansible.builtin.service:
        name: ziti-edge-tunnel
        state: started
        enabled: true
    - name: Ensure Ziti Edge Tunnel is running
      ansible.builtin.pause:
        seconds: 10
    - name: Send an HTTP Request to Test Ziti
      ansible.builtin.uri:
        url: http://httpbin.miniziti/post
        method: POST
        body_format: json
        body:
          hello: ziggy
      register: httpbin
      failed_when:
        - httpbin.status != 200
        - httpbin.json.hello != "ziggy"