Vagrant.configure("2") do |config|
    config.vm.provider :libvirt do |libvirt|
        libvirt.memory = 8192 # Amount of memory in MB
        libvirt.cpus = 8 # Number of CPUs
    end
    config.vm.box = "generic/freebsd14"
    config.vm.provision "ansible", run: "once" do |ansible|
        ansible.verbose = "vvv"
        ansible.playbook = "playbook.yml"
        ansible.extra_vars = {}
    end

    ziti_source_path = ENV['ZITI_SOURCE'] || "/home/kbingham/Sites/netfoundry/github"
    projects = ['ziti']
    projects.each do |project|
        config.vm.synced_folder "#{ziti_source_path}/#{project}", "/home/vagrant/#{project}"
    end

end
