- name: Install Ziti Edge Tunnel
  gather_facts: false
  hosts: default
  become: true

  tasks:
    - name: Copy DEB File
      ansible.builtin.copy:
        src: ./ziti-edge-tunnel.deb  # relative to playbook on Vagrant host/Ansible Controller
        dest: /tmp/ziti-edge-tunnel.deb
        owner: root
        group: root
        mode: '0644'
    - name: Install Ziti Edge Tunnel from DEB File
      ansible.builtin.apt:
        deb: /tmp/ziti-edge-tunnel.deb
    - name: Detect existing Ziti Identity
      ansible.builtin.stat:
        path: /opt/openziti/etc/identities/ziti-id.json
      register: ziti_id
    - name: Install Ziti Identity Enrollment Token
      ansible.builtin.copy:
        src: ./ziti-id.jwt  # relative to playbook on Vagrant host/Ansible Controller
        dest: /opt/openziti/etc/identities/ziti-id.jwt
        owner: root
        group: ziti
        mode: '0664'
      when: ziti_id.stat.exists == false
    - name: Start Ziti Edge Tunnel
      ansible.builtin.service:
        name: ziti-edge-tunnel
        state: started
        enabled: true
    - name: Ensure Ziti Edge Tunnel is running
      ansible.builtin.pause:
        seconds: 10
    - name: Send an HTTP Request to Test Ziti
      ansible.builtin.uri:
        url: http://httpbin.ziti/post
        method: POST
        body_format: json
        body:
          hello: ziggy
      register: httpbin
      failed_when:
        - httpbin.status != 200
        - httpbin.json.hello != "ziggy"