Vagrant.configure("2") do |config|
    config.vm.provider :libvirt do |libvirt|
        libvirt.machine_virtual_size = 128
        libvirt.memory = 8192 # Amount of memory in MB
        libvirt.cpus = 8 # Number of CPUs
    end

    config.vm.network "private_network",
        ip: "192.168.121.250",
        libvirt__network_name: "vagrant-libvirt",
        libvirt__dhcp_enabled: false,
        libvirt__forward_mode: "nat"

    # config.vm.box = "bento/ubuntu-24.04"
    # config.vm.box_version = "202407.23.0"

    #config.vm.box = "generic/ubuntu2204"      # 
    #config.vm.box = "generic/ubuntu2004"      # 
    # config.vm.box = "generic/alma9"            # Minimal distribution better suited for kernel customization
    # config.vm.box = "generic/alma8"
    # config.vm.box_version = "5.0.0"
    # growfs server

    # config.vm.box = "generic/debian10"        # panic: user: unknown userid 64342
    # config.vm.box = "generic/debian11"        # 
    config.vm.box = "generic/debian12"        # 
    # config.vm.box = "generic-x64/fedora39"
    # config.vm.box = "generic-x64/fedora38"    # 
    # config.vm.box = "generic-x64/fedora37"    # 

    # config.vm.box = "generic/ubuntu1804"      # undefined STATE_DIRECTORY
    # config.vm.box = "centos/7"                # undefined STATE_DIRECTORY

    config.vm.provision "ansible", run: "once" do |ansible|
        ansible.verbose = "vvv"
        # ansible.verbose = "v"
        ansible.playbook = "playbook.yaml"
        # ansible.extra_vars = { ansible_python_interpreter: "/usr/bin/python3" }
    end

    # Docker provisioner configuration
    config.vm.provision :docker

    # config.vm.provision "shell", inline: <<-SHELL
    #     set -euo pipefail
    #     apt-get install -y ansible
    #     ansible-galaxy collection install \
    #         git+https://github.com/openziti-test-kitchen/ansible-collection.git,repo-playbook
    #     ansible-playbook community.openziti.install_ziti_cli --connection local --inventory localhost,
    # SHELL

end
