- name: Install Ziti Router
  gather_facts: true
  hosts: default
  become: true

  vars:
    ziti_version: 0.34.0~8696390463
    ctrl_address: ctrl1.192.168.121.20.sslip.io
    ziti_token: eyJhbGciOiJSUzI1NiIsImtpZCI6IjA3NmM0ZDA4NDVmZDQwZWU1ZjU1MTA3NDhiOGFkNWU4NjYzZjFkODAiLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJodHRwczovL2N0cmwxLjE5Mi4xNjguMTIxLjIwLnNzbGlwLmlvOjEyODAiLCJzdWIiOiJ3Ri52NzdJeHkiLCJhdWQiOlsiIl0sImV4cCI6MTcxMzIyOTMxNywianRpIjoiNzRiN2UxN2EtZDhkNS00ODU1LWI1NTYtYjAxZjExYTM3N2UwIiwiZW0iOiJlcm90dCIsImN0cmxzIjpudWxsfQ.Wb5R1AnuPu0-RhU35pa3apkluld7pmxpMuGYizDhS4KrjGUDHEvbE36qz37FmYZiLXnLEqrFO9cUnYqitzdNnPEagn-Wp-rUHbLRn1x_AVazXrDSffjLwrsrXQCngaFTNOuNSOOm6SyfMRuRe60-gsLZ5MNzfy5xYLdtT9fhIuZk3bCrqzmqb2eiQPryrUkn2FOg-Igyf0MIs7MfDXcvfgE_2X6a524L1URQqBsZhNzbxo4TU6ZmA2q0_fC3auZA5jdjTzUsUhl5emCHTQjYKukr6GuTJObRpymLHOiQ0vthF5JpjQaoodT0UT111RA4bYIX7BhyvDZWvPiWjktzV7dH0pM4h4P3_OdGwKhnR2W_uTvw9ANSJLkgHe2IQ2YtloagMDwcd-Qc6Qu3rf1XwmNwYNHKXmSHErmnTzi0SVLEhIlDC8qUGeniOJUgH6CeLgy0YJfCpUnQgj44J36aQ628t6WUG395gFvK-dbMT2-LPnTQhw4EzJDYZrpTCDwi7LGQSRI_LQ6Sa06F99ftO1Z2nhLK7JM0FPa6eL1mncuckhSE31FdNvLEGEZQrZII1oe3YAfCI2iHhjNmA221AnyvmgofmwuZNGOM-J6-GQ-05mKJJvk7Q10Z93deuwhPHGJdoU5jaNBuSl55-ysbqcikSJUUR7C_qUInVjSNI5I
  tasks:
    - name: Configure RPM Repository
      ansible.builtin.copy:
        dest: /etc/yum.repos.d/openziti.repo
        mode: '0644'
        owner: root
        group: root
        content: |
          [OpenZiti]
          name=OpenZiti
          baseurl=https://packages.openziti.org/zitipax-openziti-rpm-test/redhat/$basearch
          enabled=1
          gpgcheck=0
          gpgkey=https://packages.openziti.org/zitipax-openziti-rpm-test/redhat/$basearch/repodata/repomd.xml.key
          repo_gpgcheck=1

    - name: Pin Ziti CLI version
      ansible.builtin.yum:
        name: openziti-{{ ziti_version }}
        update_cache: true
        disable_gpg_check: false
        state: present

    - name: Pin Ziti Router version
      ansible.builtin.yum:
        name: openziti-router-{{ ziti_version }}
        disable_gpg_check: false
        state: present
        # enablerepo: OpenZiti
        # skip_broken: yes
        # allow_downgrade: yes
        # install_weak_deps: no

    - name: Enable Generating a Ziti Router Configuration
      ansible.builtin.lineinfile:
        path: /opt/openziti/etc/router/service.env
        regexp: '^ZITI_BOOTSTRAP='
        line: ZITI_BOOTSTRAP=true

    - name: Set Controller Address
      ansible.builtin.lineinfile:
        path: /opt/openziti/etc/router/bootstrap.env
        regexp: '^ZITI_CTRL_ADVERTISED_ADDRESS='
        line: ZITI_CTRL_ADVERTISED_ADDRESS={{ ctrl_address }}

    - name: Set Router Address
      ansible.builtin.lineinfile:
        path: /opt/openziti/etc/router/bootstrap.env
        regexp: '^ZITI_ROUTER_ADVERTISED_ADDRESS='
        line: ZITI_ROUTER_ADVERTISED_ADDRESS=router1.{{ ansible_default_ipv4.address }}.sslip.io

    - name: Set Enrollment Token
      ansible.builtin.copy:
        dest: /opt/openziti/etc/router/.token
        content: "{{ ziti_token }}"
        mode: '0600'

    - name: Start Ziti Router
      ansible.builtin.systemd:
        name: ziti-router
        state: started
        enabled: true

    - name: Allow Ziti Router through the firewall
      ansible.posix.firewalld:
        port: 3022/tcp
        permanent: true
        state: enabled
        immediate: true
